FROM node:22.12 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

ENV PORT=3001

FROM node:22.12

WORKDIR /app
COPY --from=build /app/build /app/build

RUN npm install -g serve

EXPOSE 3001

CMD ["serve", "-s", "build"]
