GET http://localhost:3000/user


###

POST http://localhost:3000/users HTTP/1.1 
Content-Type: application/json

{
  "nome": "caio",
  "email": "caio@gmail.com",
  "idade": 17 ,
  "cpf": "12345689"
}
###
PATCH http://localhost:3000/users/8767 HTTP/1.1
Content-Type: application/json

{
  "nome": "PA",
  "email": "kroonos@gmail.com",
  "idade": 20 ,
  "cpf": "123456789"
}
###
DELETE  http://localhost:3000/users/21

